name: C/C++ CI

on:
  push:
    branches:
      - main # Run on main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: cd Dir
        run: cd CR_28

      - name: Install ARM Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Build with make
        run: make

      # - name: Run checks
      #   run: make TODO: Add more checks

